### ISSUE TITLE
Agree on git workflow for djankiserv

### ISSUE THREAD

**Issue by AntonOfTheWoods** [ankicommunity/djankiserv#12]
After working in a (well respected in France) company that always rebased before merging, I have come to appreciate the clean git history it promotes and the smaller, incremental (with feature flag activation if required) development cycle.

Given the (current and likely long-term) usages and risk profile of this project, it also seems to be a logical way to move forward here. In a large, multi-national company that has releases that will live for years and both point and minor releases on those releases, I can understand wanting to go with git flow. This project seems to merit significantly more agility.

That said, I am also all for obligatory reviews, even for me. This can become a little tricky though, if there aren't at least a couple of people who know how most of the code works.

**Comment by AntonOfTheWoods** [comment]
@VikashKothary FYI

**Comment by VikashKothary** [comment]
Hey @AntonOfTheWoods,

I agree on the agile approach and keeping the overhead as low as possible. The main thing I'm concerned with is stability. So I'm happy with any approach that will allow us develop quickly as long as that doesn't sacrifice that stability. And I'll follow your judgement on that. 

But here are some thoughts.

They way I develop is I've got a `main`/`develop` branch split. This give users to choose between a stable version of the software, or the latest version of the software. 

The workflow `feature` to `develop` is optimised to allow users to contribute quickly. The workflow `develop` to `main` is slowed down to allow code to age for stability. 

The final point is that in my opinion opinion that going fast is failing fast. So I thought a strong CI/CD pipeline is key to getting the best of both worlds. So if you want people to follow a particlar branch/commit format then I would suggest putting it into the project.

Now this ticket, seems to be about the best workflow and I don't rebased before merging is inherently bad but I personally am not a fan of using destructive git commands on the `main`/`develop`, This is because once you rebase, you can't go back to the old version of the git tree (unless you store both versions). I think it's fine for `feature` to `develop` but I would suggest using a traditional merge for `develop` to `main`. 

I also had the question, on how you would automate this? Can Github do this automatically? Or would we use a CI script?

P.S. I just googled Feature Flags and it's a really cool feature.

**Comment by AntonOfTheWoods** [comment]
> The final point is that in my opinion opinion that going fast is failing fast. So I thought a strong CI/CD pipeline is key to getting the best of both worlds. So if you want people to follow a particular branch/commit format then I would suggest putting it into the project.

This is a no brainer, however, again, while I am the only person doing any real commits, I'm not personally going to develop the code/infra for this. It takes a lot of time that is not justified unless there actually needs to be coordination. Let's call it just-in-time software industrialisation :-). One documentation PR from Istvan doesn't qualify yet!
 
> Now this ticket, seems to be about the best workflow and I don't rebased before merging is inherently bad but I personally am not a fan of using destructive git commands on the `main`/`develop`, This is because once you rebase, you can't go back to the old version of the git tree (unless you store both versions). I think it's fine for `feature` to `develop` but I would suggest using a traditional merge for `develop` to `main`.

I really don't understand your point about destructive git commands. What is destructive again? Maybe it is because in the workflows I have worked more with there is only one source of truth - `main`. Everything else is developers trying to convince their peers that they have written something that deserves its place in `main`. It gets changed, updated, cherry-picked, whatever until it is *actually born*, when it gets accepted on top of `main`'s HEAD. It is always judged on what it adds to current `main`, not with regards to some previous point in time. Unless it is a point fix on a stable release, we don't care about the past. Someone developing a branch hasn't actually done anything until their changes have been merged on top of `main`, so there is nothing that is being destroyed.

In order for this to work fluidly, stuff needs to get reviewed and merged quickly and regularly, that is for sure. But something is wrong when that is not happening anyway, so that is a non-issue. When you have this flow, you get into the habit of rebasing your branch on `main` before you start work for the day (or even morning/afternoon). Any issues you fix in place immediately, while everything is still very much in your head. Particularly because you are also expected to be reviewing and keeping an eye on everything else that is going into `main`, if you see something that is likely to mess with what you are working on you can coordinate with the other contributor directly, and if you merge someone else's code you make sure your own code is compatible with the new changes immediately after that.

> I also had the question, on how you would automate this? Can Github do this automatically? Or would we use a CI script?

The merge button for Github PRs has a down arrow which gives you three options. It's the third option. If you previously selected this option (for a project?) it preselects this for the next PR. It will refuse if there are conflicts, and you can (like I did with Istvan's PR) go through and cherry pick quickly and easily. It definitely requires a bit of getting used to but so does git. When I first started properly working with git after subversion I had a nightmare of a time. Half an hour with a patient and super helpful colleague, plenty of lightbulbs and a recognition that this was a great way to develop.

> P.S. I just googled Feature Flags and it's a really cool feature.

I guess that is how the V2 scheduler was introduced into Anki? :-)

**Comment by sandroden** [comment]
I don't think I'm really qualified to weigh in as I haven't yet even contributed anything, so I'll just state some general thoughts.
I really think that obligatory reviews would be a very effective guarantee of good quality. I support it!
That, in turn, means to agree on how the outcome must be... (technical choices, formatting...).

I'm personally more used to rebase before merging as I work in a little software house where, as @AntonOfTheWoods's case, we have one 'main' branch and branches ('topics' as we use mercurial) for the features to develop.

Another point I really would like to see is a good quality in the documentation. I really suffer from how official documentation is treated in the Anki source code: it seems a barrier for newcomers. Typically open-source projects have good documentation, and I'd willingly help in that field also.

**Comment by VikashKothary** [comment]
@AntonOfTheWoods 

>  just-in-time software industrialisation

1) Love it. Totally agree just mentioned so we're aligned. 

> Maybe it is because in the workflows I have worked more with there is only one source of truth - main

> Unless it is a point fix on a stable release, we don't care about the past.

2) Totally agree. That was the point I was trying to make but I don't think I said it properly. A destructive git command is one that changes the git history and you don't want to do that for a stable release branch. I'm happy to rebase and merge rebase feature branches. 

The only point I would make is with reverting. With merge requests, we test the feature as a whole then merge into `main`. So if it breaks `main` we could just revert to the last commit. It also means that every commit on the `main` is stable. That wouldn't be the case for a rebase merge strategy. But if I'm guessing correctly, in this strategy would we tag each merge or something which would solve that issue? 

+1 to rebasing your branch on main before you start work for the day (or even morning/afternoon). That's a really good practice for those reading.

Ngl other than that one point, rebase merging sounds like an exciting thing to try so I'm all in.

> The merge button for Github PRs has a down arrow which gives you three options. It's the third option

Yh I just saw that yesterday. Looks good to me.

> I guess that is how the V2 scheduler was introduced into Anki? 

3) That sounds good. I think I'll be a good addition to this project. But I'll take your lead with that because I've not used it myself unless environment variable configs count lol.

**Comment by VikashKothary** [comment]
@sandroden 

> I don't think I'm really qualified to weigh in 

All contributions are welcome :)

> Another point I really would like to see is a good quality in the documentation

Amen. Totally agree. I do love some good documentation. That's a PR open we've love to get your opinion in: https://github.com/ankicommunity/djankiserv/pull/6.

**Comment by AntonOfTheWoods** [comment]
> The only point I would make is with reverting. With merge requests, we test the feature as a whole then merge into `main`. So if it breaks `main` we could just revert to the last commit. It also means that every commit on the `main` is stable. That wouldn't be the case for a rebase merge strategy. But if I'm guessing correctly, in this strategy would we tag each merge or something which would solve that issue?

@VikashKothary so by "we test the feature as a whole" you mean "spend several weeks testing via armies of little (human) gremlins taping away on a keyboard to try and break something"? Like you would for a desktop app at Adobe, for example? But I disagree that you have tested anything properly at all, or at least you have not tested in a way that is in any way superior to what the rebase strategy allows for. You are starting a branch and then developing and testing code from that point X. When you come to merge back in, you are not merging back in at X, you are merging back at X+1. You have tested *nothing* at X+1. Sure, you can run automated tests again... But that ends up being strictly functionally identical to the rebase strategy, which you can also revert to X+1 (from your X+2 that you just deployed) just as easily as unmerging your feature branch.

The rebase strategy pushes you to make small changes that allow your single codebase to also support the new way of doing things. This can happen via feature flags, or simply by refactoring the existing code to do things in a way that is compatible with both the old and new. This code can be reverted at any time, because it usually happens in small batches, and always directly on head. Issues are small and very quickly fixed. You don't create "big bang" moments, like you inevitably do with large feature branches that get merged back in on a totally different main to when they started life.

When your marketing team are struggling to find new reasons for users to pay for a new version, big bang functionality dumps are good for business, so you need them. When you are providing a service, they are just disruptive - what you really want is for the exact same codebase to be serving "stable" users and "beta" users, with "beta" users having a checkbox somewhere in the backoffice saying "has new feature X activated". That way you can just do a db update somewhere to turn a feature on by default when your marketing team has their new "user day". Hopefully you will still do blue/green deployment (or whatever) to make sure the new functionality doesn't bring the sky down when it is the default setting but you (hopefully) don't have to do any schema reverts because the code and data sources with and without are exactly the same.

My personal opinion is that long-lived feature branches are a relic of the waterfall way of thinking, and rebasing is more the just-in-time way of thinking. When your organisation needs someone to blame when things go wrong, the old way is absolutely perfect. The feature manager is useless, so get rid of him and management has solved the problem, right?

**Comment by VikashKothary** [comment]
@AntonOfTheWoods 

> The rebase strategy pushes you to make small changes that allow your single codebase to also support the new way of doing things.

Based on the comments here, I did a quick Google and found this: https://trunkbaseddevelopment.com/. It sounds like what you're suggesting. It's a good read for anyone else who's interested.

I'm happy with this approach and am excited to give it a go. The article is extremely details and answered a lot of my concerns. There are some key features in this way of working such as feature flags, and branch by abstraction, which are key to their success so I would suggest making that clear as part of a CONTRIBUTING.md. Otherwise, I see a risk of people reverting to their preferred way of doing things. That being said, it sounds like an extremely powerful git workflow.

> My personal opinion is that long-lived feature branches are a relic of the waterfall way of thinking, and rebasing is more the just-in-time way of thinking

Now you'll probably notice a pattern with a lot of my comments. When I've been given a choice of this **or** that, I normally go for this **and** that. The same is true here. I see Truck Based Development favoured by throughs building Consumer-facing and SAAS applications and Git Flow favoured by Enterprise-facing and non-Cloud Native applications applications. I see this project somewhere down the middle so I think either can work.

Regardless, I feel like this project will benefit with the speed-boosts that come with your proposed git workflow (as long as we get quick reviews on PRs so that people aren't blocked).

**Comment by AntonOfTheWoods** [comment]
> Regardless, I feel like this project will benefit with the speed-boosts that come with your proposed git workflow (as long as we get quick reviews on PRs so that people aren't blocked).

Yep, as the article mentioned, they use this a lot at Google. Probably the reason we used it at my last place was that our ex-Googlers were, unsurprisingly, very influential in what workflows we adopted.

And I definitely agree - review speed is absolutely crucial. We were expressly forbidden from asking for a review within 24h of submitting (unless there was a prod issue, of course!) but if 24h had passed you could be sure it got a mention at the next standup, if it hadn't already been mentioned on slack!

So are we agreed then? Can we close?

**Comment by VikashKothary** [comment]
Well I think the action here is to enforce this somewhere. I suggest creating a CONTRIBUTING.md e.g. https://gist.github.com/PurpleBooth/b24679402957c63ec426.
