### ISSUE TITLE
Dockerfile for quick server setup

### ISSUE THREAD

**Issue by k0mmsussert0d** [ankicommunity/djankiserv#26]
I think it'd be beneficial and inviting for new users to have a Dockerfile, ideally with an image hosted at Docker Hub available. If you share my opinion, I'd be glad to work on it.

**Comment by AntonOfTheWoods** [comment]
Hi @k0mmsussert0d . There are dockerfiles in https://github.com/ankicommunity/djankiserv/tree/master/images. That said, I'm pretty certain there will be incompatibilities with recent Anki client versions, so you might want to go with the other project (https://github.com/ankicommunity/anki-sync-server) if you don't need Django specifically. I created this project but realised that both Anki and Django are "legacy" in many ways, and it was simply far too much work to try and do what I wanted with these, rather than completely reimplement what I needed with custom UI code and FastAPI. Django is great for hobby sites but the world has now moved on (async) and they still haven't.

**Comment by VikashKothary** [comment]
Hi @k0mmsussert0d, Anton mentioned there is a Dockerfile in this repo, but also a dockerfile in the following repository: https://github.com/ankicommunity/anki-devops-services/tree/develop/services/djankiserv. We have a `ankicommunity` docker hub account but I don't believe the CI has been created to push to it. See: https://github.com/ankicommunity/anki-devops-services/issues/11. Contributions are always welcome. 

@AntonOfTheWoods I personally think that the sync server and this project have different use cases and both are important. I've created a new ticket regarding your critique: https://github.com/ankicommunity/djankiserv/issues/27. I do plan on working on this so let me know if you have any thoughts regarding the topic.

**Comment by AntonOfTheWoods** [comment]
Actually @VikashKothary , I think what needs to be done is implement a fully web-based replacement for Anki. Basically, implement something with most of the functionality entirely in the browser. Offline-first works pretty damn well, and if you absolutely insist on having a "permanent" shell, you can just host in Electron. 

While I can certainly attest that there are MASSIVE annoyances with the web platform, there is no longer any real justification for most usecases that don't make heavy use of secure APIs (location, etc.). Performance and power usage are fine and have been for years now, saying otherwise is just disingenuous. Attempting to maintain an API for a client eco-system based on obsolete tech is just silly, particularly when the upstream author is trying to make a living out of a proprietary sync system, and not providing any docs. There are lots of arguments to be made for certain types of client but none of them apply to SRS. All of the user extensions are in JS anyway, and using a crappy engine, so it's basically all disadvantages from my point of view. 

The time would be much better spent on a new, modern ecosystem. I have already spent literally thousands of hours trying to extend this one and realised I was going to spend much less starting from scratch. Everyone else should to!

**Comment by VikashKothary** [comment]
Hi @AntonOfTheWoods, I think we're pollution this thread with off-topic discuss. Can you create a new ticket with your exact recommendation so we can discuss it further?

I agree with your vision of a "new, modern ecosystem." so would be interested in discussing it further. I believe with the appropriate architecture you should be able to have the best of both worlds (old and new functionality) with minimal effort. 

Also it's important to note that not everyone has thousands of hours to build a Anki replacement so you'll alienate a lot of users which such talk. :)

**Comment by k0mmsussert0d** [comment]
Thank you everyone for pointing out to Dockerfile and alternative solutions. I think this issue may be closed now.
